#!/usr/bin/env bash
# Client configuration file
# file with user config
Host 100.25.204.254
PasswordAuthentication no
IdentityFile ~/.ssh/school
SendENV LANG LC_*
HashKnownHosts yes
GSSAPIAuthentication yes
GSSAPIDelegateCredentials no
